### ISSUE TITLE
ClassArtemisSerializer

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#439]
- fastest/most efficient solution; GC-friendly
- ~~save to source or directly to `.class`~~ compile to class
- ~~load from class~~ Prefab intercepts via `@Prefab.Compiled(Class)`; set by artemis-odb plugin
- offer way to auto-convert json blob -> `.class`, to simplify making it into an optimization at build-time
  - artemis-odb plugin (think `compile-prefabs` task)

The auto-convert route is probably the most sane use-case; out-of-sync identifiers in json blobs are easier to fix than renamed references in class files. Only "release" code really benefits from faster loading times/less GC; as such, it'll probably end up in the default maven/gradle plugins.

## TODO
- [x] entity json -> nodes
- [ ] generate createEntities
- [ ] compile file
- [ ] node should understand entity references
- [ ] map ref vs new entityIds
- [ ] node: arrays
- [ ] node: maps
- [ ] asm: find prefabs
- [ ] option: delete original json
- [ ] tag prefab `@Prefab.Compiled`

development branch: [origin/439-compiled-serialization](https://github.com/junkdog/artemis-odb/tree/439-compiled-serialization)

**Comment by Namek** [comment]
what about some bandtwith-efficient approach rather than JSON? I'm thinking of https://github.com/Namek/artemis-odb-entity-tracker here

**Comment by junkdog** [comment]
The kryo backend produces smaller output (2/3 or so compared to json); but if you want to optimize bandwidth you probably only want to send the deltas (I'd make components atomic units). The specifics are a bit illusive though, and not really supported by the current serialization mechanism - unless you roll a custom serialization backend which internally filters and sends the correct deltas.

**Comment by junkdog** [comment]
development branch: [origin/439-compiled-serialization](https://github.com/junkdog/artemis-odb/tree/439-

**Comment by DaanVanYperen** [comment]
@junkdog is this salvageable? otherwise perhaps close.

**Comment by DaanVanYperen** [comment]
Just some observations after updating the wiki and #510.

- [ ] BasePrefab hierarchy feels a bit smelly. It's basically just a convenience harness that has some json logic leaking in. Maybe cleaner to delegate all loading logic to the reader? (including the `SERIALIZER` generic and abstract `create`). Will make it a bit easier to understand and create custom implementations. 
- [ ] The naming feels a bit unidiomatic. I realize idiomatic names might make it a bit too generic, but make it easier to find in wiki etc. Something like `EntityTemplate`/`CachedEntityTemplate`?
- [ ] `SaveFileFormat` could use a bit of quality of life and documentation improvements, for example allow fetching entities by id, docu for serializationtags and `SaveFileFormat.get()` .
- [ ] Couldn't find it, is there DI for prefabs like for the component mappers?

**Comment by junkdog** [comment]
> BasePrefab hierarchy feels a bit smelly. It looks like a convenience harness but has some json logic leaking in.

Hmm, where do you mean? It's a dependency on artemis' serializer, but not json afaik. Should definitely provide a custom reader though - I thought  there were at least some basic tests demonstrating custom ones.

> The naming feels a bit unidiomatic.

I stole it from Unity3d; mostly 

> SaveFileFormat could use a bit of quality of life and documentation improvements, for example allow fetching entities by id,

Agreed; I'll see about expanding with more annotated examples. The impl itself begs for a cleaner rewrite, but that is unlikely to happen anytime soon.

Not sure about fetching by id, or which id do you mean? Any id recorded in the json is pretty volatile (id:s will likely change if re-saved).

> Couldn't find it, is there DI for prefabs like for the component mappers?

yup; all new-ish artemis facilities auto-inject (where appropriate).

**Comment by junkdog** [comment]
> is this salvageable? otherwise perhaps close.

with some work, yes, but still quite a few things remain. I can "manually" run basic compiled prefabs  on my computer (compiler + bytecode transformations not done). moved it to 2.3.0.

**Comment by DaanVanYperen** [comment]
@junkdog cleaning out stale branches, still sponsoring this?

**Comment by junkdog** [comment]
Ice-boxing this for now, but I wouldn't mind revisiting it - if it fulfills a need.
